version: '8.0.41'
services:
  mysql:
    image: mysql:latest
    container_name: 'etudiantdatabase'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'etudiantdb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - "3307:3307"
    volumes:
      - ./mysql_data:/var/lib/mysql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
